<a href="https://colab.research.google.com/github/tadiri/BayesCog_Wien/blob/master/QLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import gym

env = gym.make("FrozenLake-v1",new_step_api=True)
#env = gym.make("Taxi-v3",new_step_api=True)
n_observations = env.observation_space.n
n_actions = env.action_space.n

#We start with a Q table of "all zeros"
Q_table = np.zeros((n_observations,n_actions))
print(Q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:


#the number of episodes we use for training
n_episodes = 50000

#maximum of transitions per episode
max_traj_per_episode = 100

#Epsilon-Greedy with start value 1
epsilon = 1

#value for decreasing Epsilon per step
epsilon_decay = 0.0001

# minimum of exploration proba
min_epsilon = 0.001

#discounted factor
gamma = 1

#learning rate
lr = 0.0001

total_rewards_episode = list()
rewards_per_episode = list()


# we train for a number of episodes
for e in range(n_episodes):
    #every time we start, we reset the environment
    current_state = env.reset()
    done = False

    #we sum the individual rewards an agent gets per episode
    total_episode_reward = 0

    for i in range(max_traj_per_episode):
        # Epsilon-Greedy calculation - do we explore, or exploit?
        if np.random.uniform(0,1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(Q_table[current_state,:])

        # we perform the selected action on the enviroment and get (1) the next state we are landing in, (2) the reward of the last action, (3) information if the episode ended
        next_state, reward, done, truncated , info = env.step(action)
        # observation, reward, done, info

        # After each step, we update our Q-value for the last transition according to Q-learning
        Q_table[current_state, action] = Q_table[current_state, action] +lr*(reward + gamma*max(Q_table[next_state,:])-Q_table[current_state, action])

        # After each step, we add the reward of the last action (if any) to our episode reward
        total_episode_reward = total_episode_reward + reward

        # If the last action yieleded to the end of an episode, we stop and continue with a nuew run
        if done:
            break
        current_state = next_state
    #We reduce epsilon to slowly move from exploration to exploitation
    epsilon = max(min_epsilon, np.exp(-epsilon_decay*e))
    #At the end of every episode, we store the cummulative reward that we got
    rewards_per_episode.append(total_episode_reward)

    if(e%1000==0):
      print(epsilon)



#at the end of training, we also show how our Q-values have been updated
print(Q_table)

#We also show in steps of of 1000 if and how the average reward has been increased
print("Mean rewards")
for i in range(n_episodes//1000):
    print((i+1)*1000,": mean espiode reward: ", np.mean(rewards_per_episode[1000*i:1000*(i+1)]))

1.0
0.9048374180359595
0.8187307530779818
0.7408182206817179
0.6703200460356393
0.6065306597126334
0.5488116360940264
0.49658530379140947
0.44932896411722156
0.4065696597405991
0.36787944117144233
0.33287108369807955
0.30119421191220214
0.2725317930340126
0.24659696394160643
0.22313016014842982
0.20189651799465538
0.1826835240527346
0.16529888822158653
0.14956861922263504
0.1353352832366127
0.1224564282529819
0.11080315836233387
0.1002588437228037
0.09071795328941251
0.0820849986238988
0.07427357821433388
0.06720551273974976
0.06081006262521795
0.05502322005640721
0.049787068367863944
0.0450492023935578
0.04076220397836621
0.036883167401239994
0.033373269960326066
0.0301973834223185
0.02732372244729256
0.024723526470339388
0.02237077185616559
0.02024191144580438
0.01831563888873418
0.016572675401761237
0.014995576820477703
0.013568559012200934
0.012277339903068436
0.011108996538242306
0.010051835744633576
0.009095277101695816
0.00822974704902003
0.007446583070924338
[[5.85488844e-02 7.